import type { TutorialMeta } from "./types";

/**
 * Static registry of fully-authored tutorials, keyed by slug.
 *
 * Metadata only — no MDX component imports — so this module stays trivially
 * unit-testable. The route resolves slug → MDX content separately. Section
 * `id`s must match the heading ids inside the corresponding MDX file; they
 * drive the table of contents and in-page anchors.
 */
export const tutorials: Record<string, TutorialMeta> = {
  "url-shortener": {
    slug: "url-shortener",
    title: "Design a URL Shortener",
    description:
      "A complete, interview-grade walkthrough: requirements, capacity math, APIs, key generation, architecture, caching, consistency, scaling, resiliency, and security.",
    difficulty: "Foundational",
    readingMinutes: 35,
    concepts: ["Key generation", "Caching", "Read-heavy scaling", "Partitioning"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "key-generation", label: "Key Generation", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "storage-partitioning", label: "Storage & Partitioning", depth: "advanced" },
      { id: "caching", label: "Caching", depth: "advanced" },
      { id: "consistency-concurrency", label: "Consistency & Concurrency", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "security-abuse", label: "Security & Abuse", depth: "advanced" },
      { id: "observability", label: "Observability", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "rate-limiter": {
    slug: "rate-limiter",
    title: "Design a Rate Limiter",
    description:
      "An algorithm-first, interview-grade walkthrough of a distributed rate limiter: the five classic algorithms, limit policies, the allow/throttle API, distributed counting, consistency, scaling, and failure modes.",
    difficulty: "Foundational",
    readingMinutes: 30,
    concepts: ["Token bucket", "Sliding window", "Distributed counters", "Fail-open"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "limit-policies", label: "Limit Policies & Keys", depth: "interview-ready" },
      { id: "algorithms", label: "Algorithms", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "distributed-counting", label: "Distributed Counting", depth: "advanced" },
      { id: "consistency-races", label: "Consistency & Races", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "observability", label: "Observability", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "pastebin": {
    slug: "pastebin",
    title: "Design a Pastebin",
    description:
      "An interview-grade walkthrough of a Pastebin: storing large text blobs in object storage with metadata in a database, expiry and TTL, CDN delivery of immutable content, privacy and access control, scaling, and failure modes.",
    difficulty: "Foundational",
    readingMinutes: 32,
    concepts: ["Blob storage", "TTL & expiry", "CDN", "Access control"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "blob-metadata-split", label: "Blob & Metadata Storage", depth: "advanced" },
      { id: "expiry-and-ttl", label: "Expiry & TTL", depth: "advanced" },
      { id: "caching-cdn", label: "Caching & CDN", depth: "advanced" },
      { id: "access-control", label: "Access Control & Privacy", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "security-abuse", label: "Security & Abuse", depth: "advanced" },
      { id: "observability", label: "Observability", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "notification-service": {
    slug: "notification-service",
    title: "Design a Notification Service",
    description:
      "An interview-grade walkthrough of a multi-channel notification service: an asynchronous fan-out pipeline over message queues, at-least-once delivery made safe with idempotency, retries with backoff and a dead-letter queue, user preferences and rate limiting, scaling, and failure modes.",
    difficulty: "Intermediate",
    readingMinutes: 34,
    concepts: ["Fan-out", "Message queues", "Idempotency", "Retries"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "fanout-pipeline", label: "Fan-out Pipeline", depth: "advanced" },
      { id: "delivery-guarantees", label: "Delivery Guarantees & Idempotency", depth: "advanced" },
      { id: "retries-dlq", label: "Retries & Dead-Letter Queue", depth: "advanced" },
      { id: "user-preferences", label: "Preferences & Rate Limiting", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "security-abuse", label: "Security & Abuse", depth: "advanced" },
      { id: "observability", label: "Observability", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "ticket-booking": {
    slug: "ticket-booking",
    title: "Design a Ticket Booking System",
    description:
      "An interview-grade walkthrough of a ticket booking system that sells limited inventory under heavy contention without overselling: the seat reservation lifecycle, optimistic vs pessimistic concurrency control, strong consistency on inventory, the idempotent hold-pay-confirm payment saga, high-contention on-sale management, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["Distributed locking", "Inventory", "Strong consistency", "Reservations"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "reservation-lifecycle", label: "Reservation Lifecycle", depth: "advanced" },
      { id: "concurrency-control", label: "Concurrency Control", depth: "advanced" },
      { id: "strong-consistency", label: "Strong Consistency", depth: "advanced" },
      { id: "payment-saga", label: "Payment & Booking Saga", depth: "advanced" },
      { id: "high-contention", label: "High-Contention On-Sales", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "security-abuse", label: "Security & Abuse", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "payment-system": {
    slug: "payment-system",
    title: "Design a Payment System",
    description:
      "An interview-grade walkthrough of a payment system: exactly-once processing with idempotency keys, the immutable double-entry ledger, the payment lifecycle state machine, the dual-write problem and the transactional outbox, reconciliation against external providers, security and compliance, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 37,
    concepts: ["Double-entry ledger", "Idempotency", "Consistency", "Reconciliation"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "idempotency", label: "Idempotency & Exactly-Once", depth: "advanced" },
      { id: "double-entry-ledger", label: "The Double-Entry Ledger", depth: "advanced" },
      { id: "payment-lifecycle", label: "Payment Lifecycle & State Machine", depth: "advanced" },
      { id: "distributed-transactions", label: "Distributed Transactions & the Dual-Write Problem", depth: "advanced" },
      { id: "reconciliation", label: "Reconciliation", depth: "advanced" },
      { id: "security-compliance", label: "Security & Compliance", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "video-streaming": {
    slug: "video-streaming",
    title: "Design a Video Streaming Platform",
    description:
      "An interview-grade walkthrough of a video-on-demand platform: resumable upload and ingestion, the asynchronous transcoding pipeline (the rendition ladder and segmentation), adaptive bitrate streaming, CDN-dominated delivery and caching, storage and cost, scaling, failure modes, and security/DRM.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["Transcoding", "Adaptive bitrate", "CDN", "Object storage"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "upload-ingestion", label: "Upload & Ingestion", depth: "advanced" },
      { id: "transcoding-pipeline", label: "Transcoding Pipeline", depth: "advanced" },
      { id: "adaptive-bitrate-streaming", label: "Adaptive Bitrate Streaming", depth: "advanced" },
      { id: "cdn-delivery", label: "CDN Delivery", depth: "advanced" },
      { id: "storage-and-cost", label: "Storage & Cost", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "security-drm", label: "Security & DRM", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "distributed-cache": {
    slug: "distributed-cache",
    title: "Design a Distributed Cache",
    description:
      "An interview-grade walkthrough of a sharded, replicated in-memory distributed cache: consistent hashing and virtual nodes, eviction policies, replication and tunable consistency, hot-key mitigation, cache stampede protection, write policies and invalidation, scaling, and failure modes.",
    difficulty: "Intermediate",
    readingMinutes: 34,
    concepts: ["Consistent hashing", "Eviction", "Replication", "Hot keys"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "consistent-hashing", label: "Consistent Hashing", depth: "advanced" },
      { id: "eviction-policies", label: "Eviction Policies", depth: "advanced" },
      { id: "replication-consistency", label: "Replication & Consistency", depth: "advanced" },
      { id: "hot-keys", label: "Hot Keys & Hotspots", depth: "advanced" },
      { id: "cache-stampede", label: "Cache Stampede", depth: "advanced" },
      { id: "write-policies", label: "Write Policies & Invalidation", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "collaborative-doc-editor": {
    slug: "collaborative-doc-editor",
    title: "Design a Collaborative Document Editor",
    description:
      "An interview-grade walkthrough of a real-time collaborative document editor: concurrent editing without lost updates, operational transformation versus CRDTs, the real-time websocket sync protocol with optimistic local apply, presence and awareness, op-log persistence and history, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["CRDT / OT", "Real-time sync", "Conflict-free merge", "Presence"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "concurrent-editing", label: "The Concurrent-Editing Problem", depth: "advanced" },
      { id: "operational-transformation", label: "Operational Transformation", depth: "advanced" },
      { id: "crdts", label: "Conflict-Free Replicated Data Types", depth: "advanced" },
      { id: "realtime-sync", label: "Real-Time Sync", depth: "advanced" },
      { id: "presence-awareness", label: "Presence & Awareness", depth: "advanced" },
      { id: "persistence-history", label: "Persistence & History", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "distributed-logging": {
    slug: "distributed-logging",
    title: "Design a Distributed Logging Platform",
    description:
      "An interview-grade walkthrough of a distributed logging platform: the firehose ingestion pipeline and durable buffer, parsing and structured logs, indexing for search, storage tiers and retention, query and search over huge time ranges, cost and cardinality control, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["Ingestion pipeline", "Indexing", "Search", "Retention"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "ingestion-pipeline", label: "Ingestion Pipeline & Buffering", depth: "advanced" },
      { id: "parsing-structure", label: "Parsing & Structured Logs", depth: "advanced" },
      { id: "indexing", label: "Indexing for Search", depth: "advanced" },
      { id: "storage-tiers", label: "Storage Tiers & Retention", depth: "advanced" },
      { id: "query-search", label: "Query & Search", depth: "advanced" },
      { id: "cost-cardinality", label: "Cost, Sampling & Cardinality", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "cloud-drive": {
    slug: "cloud-drive",
    title: "Design a Cloud Drive",
    description:
      "An interview-grade walkthrough of a cloud drive (Dropbox / Google Drive style): the metadata/block split, chunking and content-addressed deduplication, delta sync, the cursor + notification sync protocol, the metadata store and namespace, sharing and permissions, versioning and history, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["Object storage", "Deduplication", "Delta sync", "Metadata"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "chunking-dedup", label: "Chunking & Deduplication", depth: "advanced" },
      { id: "delta-sync", label: "Delta Sync", depth: "advanced" },
      { id: "sync-protocol", label: "Sync Protocol & Notifications", depth: "advanced" },
      { id: "metadata-store", label: "Metadata Store & Namespace", depth: "advanced" },
      { id: "sharing-permissions", label: "Sharing & Permissions", depth: "advanced" },
      { id: "versioning-history", label: "Versioning & History", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "maps-navigation": {
    slug: "maps-navigation",
    title: "Design Maps and Navigation",
    description:
      "An interview-grade walkthrough of a maps and navigation service: the road network as a directed weighted graph, why Dijkstra and A* don't scale, precomputation with contraction hierarchies and customizable route planning, map matching and geocoding, live traffic and ETA from GPS probes, CDN map-tile serving, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["Graph routing", "Geospatial indexing", "Traffic modeling", "Precomputation"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "road-graph", label: "The Road Network as a Graph", depth: "advanced" },
      { id: "shortest-path", label: "Shortest-Path Routing", depth: "advanced" },
      { id: "precomputation", label: "Precomputation & Hierarchies", depth: "advanced" },
      { id: "map-matching", label: "Map Matching & Geocoding", depth: "advanced" },
      { id: "traffic-eta", label: "Live Traffic & ETA", depth: "advanced" },
      { id: "tile-serving", label: "Map Tile Serving", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "distributed-job-scheduler": {
    slug: "distributed-job-scheduler",
    title: "Design a Distributed Job Scheduler",
    description:
      "An interview-grade walkthrough of a distributed job scheduler: scheduling and time triggers, reliable at-least-once execution, leasing and leader-election coordination, idempotency and exactly-once effects, retries with backoff and dead-letter, the thundering herd of synchronized firings, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["At-least-once execution", "Leasing", "Time-based triggers", "Idempotency"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "scheduling-triggers", label: "Scheduling & Time Triggers", depth: "advanced" },
      { id: "reliable-execution", label: "Reliable Execution & At-Least-Once", depth: "advanced" },
      { id: "leasing-coordination", label: "Leasing & Coordination", depth: "advanced" },
      { id: "idempotency-exactly-once", label: "Idempotency & Exactly-Once Effects", depth: "advanced" },
      { id: "retries-failures", label: "Retries, Backoff & Failure Handling", depth: "advanced" },
      { id: "hot-partitions", label: "Hot Partitions & the Thundering Herd", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "api-gateway": {
    slug: "api-gateway",
    title: "Design an API Gateway",
    description:
      "An interview-grade walkthrough of an API gateway: the single edge that fronts a fleet of microservices — request routing and service discovery, offloaded authentication and authorization, rate limiting and quotas, the control-plane/data-plane split for config distribution, resilience (timeouts, retries, circuit breaking) and observability, scaling, and failure modes.",
    difficulty: "Intermediate",
    readingMinutes: 34,
    concepts: ["Routing", "AuthN/AuthZ", "Rate limiting", "Observability"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "request-lifecycle", label: "Request Lifecycle & the Filter Chain", depth: "advanced" },
      { id: "routing-discovery", label: "Routing & Service Discovery", depth: "advanced" },
      { id: "auth", label: "Authentication & Authorization", depth: "advanced" },
      { id: "rate-limiting", label: "Rate Limiting & Quotas", depth: "advanced" },
      { id: "control-data-plane", label: "Control Plane & Data Plane", depth: "advanced" },
      { id: "resilience-observability", label: "Resilience & Observability", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "web-crawler": {
    slug: "web-crawler",
    title: "Design a Web Crawler",
    description:
      "An interview-grade walkthrough of a web crawler: the URL frontier (priority and politeness queues), robots.txt and per-host politeness, URL and content deduplication with bloom filters and fingerprints, DNS resolution and fetching at scale, freshness-aware re-crawl scheduling, crawler traps and robustness, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["Frontier queue", "Dedup & hashing", "Politeness", "Scheduling"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "url-frontier", label: "The URL Frontier", depth: "advanced" },
      { id: "politeness", label: "Politeness & robots.txt", depth: "advanced" },
      { id: "dedup", label: "URL & Content Deduplication", depth: "advanced" },
      { id: "dns-fetching", label: "DNS Resolution & Fetching", depth: "advanced" },
      { id: "freshness-scheduling", label: "Freshness & Re-crawl Scheduling", depth: "advanced" },
      { id: "traps-robustness", label: "Crawler Traps & Robustness", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "search-autocomplete": {
    slug: "search-autocomplete",
    title: "Design Search Autocomplete",
    description:
      "An interview-grade walkthrough of search autocomplete (typeahead): a trie with precomputed top-k at every node, ranking by popularity and recency with safety filtering, a batch query-log aggregation pipeline that builds and publishes the ranked index, an in-memory replicated serving tier under a tight latency budget, a real-time trending layer for freshness, typo tolerance and personalization, scaling, and failure modes.",
    difficulty: "Intermediate",
    readingMinutes: 34,
    concepts: ["Trie", "Top-k ranking", "Low latency", "Precomputation"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "trie-topk", label: "The Trie & Precomputed Top-K", depth: "advanced" },
      { id: "ranking-scoring", label: "Ranking, Filtering & Safety", depth: "advanced" },
      { id: "data-pipeline", label: "Building the Index from Query Logs", depth: "advanced" },
      { id: "serving-layer", label: "Serving, Sharding & the Latency Budget", depth: "advanced" },
      { id: "freshness-trending", label: "Freshness & Trending Queries", depth: "advanced" },
      { id: "fuzzy-personalization", label: "Typo Tolerance & Personalization", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
  "news-feed": {
    slug: "news-feed",
    title: "Design a News Feed",
    description:
      "An interview-grade walkthrough of a news feed (home timeline): fan-out on write vs read, the hybrid model for hot users (celebrities), relevance feed ranking, feed storage as post-ID lists hydrated from a post store, the asynchronous fan-out pipeline, the read path with pagination and freshness, scaling, and failure modes.",
    difficulty: "Advanced",
    readingMinutes: 36,
    concepts: ["Fan-out strategies", "Ranking", "Hot users", "Caching"],
    sections: [
      { id: "interview-framing", label: "Interview Framing", depth: "fundamentals" },
      { id: "requirements", label: "Requirements", depth: "interview-ready" },
      { id: "capacity-estimates", label: "Capacity Estimates", depth: "interview-ready" },
      { id: "entity-model", label: "Entity Model", depth: "interview-ready" },
      { id: "api-design", label: "API Design", depth: "interview-ready" },
      { id: "high-level-architecture", label: "High-Level Architecture", depth: "interview-ready" },
      { id: "detailed-flows", label: "Detailed Flows", depth: "interview-ready" },
      { id: "fanout-models", label: "Fan-out: Write vs Read", depth: "advanced" },
      { id: "hybrid-hot-users", label: "The Hybrid Model & Hot Users", depth: "advanced" },
      { id: "feed-ranking", label: "Feed Ranking", depth: "advanced" },
      { id: "feed-storage-hydration", label: "Feed Storage, Hydration & Caching", depth: "advanced" },
      { id: "fanout-pipeline", label: "The Fan-out Pipeline", depth: "advanced" },
      { id: "read-path-consistency", label: "Read Path: Pagination & Freshness", depth: "advanced" },
      { id: "scalability-evolution", label: "Scalability & Evolution", depth: "advanced" },
      { id: "resiliency-failure-modes", label: "Resiliency & Failure Modes", depth: "advanced" },
      { id: "tradeoffs-alternatives", label: "Trade-offs & Alternatives", depth: "advanced" },
      { id: "interview-summary", label: "Interview Summary", depth: "interview-ready" },
      { id: "knowledge-checks-faq", label: "Knowledge Checks & FAQ", depth: "fundamentals" },
    ],
  },
};

export function getTutorial(slug: string): TutorialMeta | undefined {
  return tutorials[slug];
}
